version: '3.5'
services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./data/init/:/docker-entrypoint-initdb.d
      - ./data/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  # files:
  #   image: minio
  #   # todo

  # app
  # api
